name: CI

on: [push, pull_request]

jobs:
  commitlint:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
      - name: Install commitlint dependencies
        run: |
          npm install --save-dev commitlint @commitlint/config-conventional

      - name: Validate last commit on push
        if: github.event_name == 'push'
        run: npx commitlint --last --verbose

      - name: Validate all PR commits
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
